--- #YAML:1.0
name:               HTTP-Cookies-Opera
version:            0.07
abstract:           Cookie storage and management for Opera
author:
    - gray <gray@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.82
requires:
    HTTP::Cookies:  0
    parent:         0
resources:
    repository:  http://github.com/gray/http-cookies-opera
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
